"""add courses layouts and holes tables

Revision ID: 2745f5fd6c00
Revises: b286f196e971
Create Date: 2026-08-22 23:01:02.221328

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2745f5fd6c00'
down_revision: Union[str, Sequence[str], None] = 'b286f196e971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'UNLISTED', name='coursevisibility'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'FLAGGED', name='coursestatus'), nullable=False),
    sa.Column('osm_id', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # geoalchemy2 creates the GIST index on `location` automatically via a
    # DDL event tied to the Geography column type — no explicit create_index.
    op.create_index(op.f('ix_courses_created_by_id'), 'courses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_table('layouts',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hole_count', sa.Integer(), nullable=False),
    sa.Column('par_total', sa.Integer(), nullable=False),
    sa.Column('total_distance_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layouts_course_id'), 'layouts', ['course_id'], unique=False)
    op.create_table('holes',
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('tee_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('basket_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('elevation_delta_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layout_id', 'number', name='uq_holes_layout_number')
    )
    # geoalchemy2 creates the GIST indexes on tee_location/basket_location
    # automatically via a DDL event tied to the Geography column type.
    op.create_index(op.f('ix_holes_layout_id'), 'holes', ['layout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holes_layout_id'), table_name='holes')
    op.drop_table('holes')
    op.drop_index(op.f('ix_layouts_course_id'), table_name='layouts')
    op.drop_table('layouts')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_by_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
    sa.Enum(name='coursestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='coursevisibility').drop(op.get_bind(), checkfirst=True)
