"""add play streaks table

Revision ID: 399f1d07c33e
Revises: d195c2392446
Create Date: 2026-08-24 00:23:43.251814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '399f1d07c33e'
down_revision: Union[str, Sequence[str], None] = 'd195c2392446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_streaks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_played_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_streaks_user_id'), 'play_streaks', ['user_id'], unique=True)
    # NOTE: autogenerate wrongly detects 'uq_friendships_unordered_pair' as removed
    # because it's a raw-SQL functional index (LEAST/GREATEST) not represented in
    # the ORM metadata. Do NOT drop it here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_play_streaks_user_id'), table_name='play_streaks')
    op.drop_table('play_streaks')
    # ### end Alembic commands ###
