"""add mutation logs table for sync push deduplication

Revision ID: 48f4fa4f1d75
Revises: 399f1d07c33e
Create Date: 2026-08-24 01:32:38.911810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f4fa4f1d75'
down_revision: Union[str, Sequence[str], None] = '399f1d07c33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutation_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mutation_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mutation_id', name='uq_mutation_logs_user_mutation')
    )
    op.create_index(op.f('ix_mutation_logs_mutation_id'), 'mutation_logs', ['mutation_id'], unique=False)
    op.create_index(op.f('ix_mutation_logs_user_id'), 'mutation_logs', ['user_id'], unique=False)
    # NOTE: autogenerate wrongly detects 'uq_friendships_unordered_pair' as removed
    # because it's a raw-SQL functional index (LEAST/GREATEST) not represented in
    # the ORM metadata. Do NOT drop it here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutation_logs_user_id'), table_name='mutation_logs')
    op.drop_index(op.f('ix_mutation_logs_mutation_id'), table_name='mutation_logs')
    op.drop_table('mutation_logs')
    # ### end Alembic commands ###
