"""add round and scoring tables

Revision ID: 999ffb3df0f8
Revises: bf77c68eefbc
Create Date: 2026-08-23 09:43:50.816881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999ffb3df0f8'
down_revision: Union[str, Sequence[str], None] = 'bf77c68eefbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='roundstatus'), nullable=False),
    sa.Column('is_practice', sa.Boolean(), nullable=False),
    sa.Column('weather_note', sa.String(), nullable=True),
    sa.Column('client_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_created_by_id'), 'rounds', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_rounds_layout_id'), 'rounds', ['layout_id'], unique=False)
    op.create_table('round_players',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_scorekeeper', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(user_id IS NULL) != (guest_name IS NULL)', name='ck_round_players_exactly_one_of_user_or_guest'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_players_round_id'), 'round_players', ['round_id'], unique=False)
    op.create_index(op.f('ix_round_players_user_id'), 'round_players', ['user_id'], unique=False)
    op.create_table('hole_scores',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('round_player_id', sa.UUID(), nullable=False),
    sa.Column('hole_id', sa.UUID(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=False),
    sa.Column('penalty_strokes', sa.Integer(), nullable=False),
    sa.Column('is_circle_hit', sa.Boolean(), nullable=True),
    sa.Column('is_fairway_hit', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['round_player_id'], ['round_players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_player_id', 'hole_id', name='uq_hole_scores_player_hole')
    )
    op.create_index(op.f('ix_hole_scores_hole_id'), 'hole_scores', ['hole_id'], unique=False)
    op.create_index(op.f('ix_hole_scores_round_id'), 'hole_scores', ['round_id'], unique=False)
    op.create_index(op.f('ix_hole_scores_round_player_id'), 'hole_scores', ['round_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hole_scores_round_player_id'), table_name='hole_scores')
    op.drop_index(op.f('ix_hole_scores_round_id'), table_name='hole_scores')
    op.drop_index(op.f('ix_hole_scores_hole_id'), table_name='hole_scores')
    op.drop_table('hole_scores')
    op.drop_index(op.f('ix_round_players_user_id'), table_name='round_players')
    op.drop_index(op.f('ix_round_players_round_id'), table_name='round_players')
    op.drop_table('round_players')
    op.drop_index(op.f('ix_rounds_layout_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_created_by_id'), table_name='rounds')
    op.drop_table('rounds')
    # ### end Alembic commands ###
    sa.Enum(name='roundstatus').drop(op.get_bind(), checkfirst=True)
