"""add is_partial to rounds

Revision ID: b1598d12cee8
Revises: 999ffb3df0f8
Create Date: 2026-08-23 13:28:06.960327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1598d12cee8'
down_revision: Union[str, Sequence[str], None] = '999ffb3df0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rounds',
        sa.Column('is_partial', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'is_partial')
    # ### end Alembic commands ###
