"""add user layout stats table

Revision ID: bc2d7a5cd001
Revises: e08b9a327d94
Create Date: 2026-08-23 21:16:08.543715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2d7a5cd001'
down_revision: Union[str, Sequence[str], None] = 'e08b9a327d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_layout_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('total_score_to_par', sa.Integer(), nullable=False),
    sa.Column('best_score_to_par', sa.Integer(), nullable=True),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'layout_id', name='uq_user_layout_stats_user_layout')
    )
    op.create_index(op.f('ix_user_layout_stats_layout_id'), 'user_layout_stats', ['layout_id'], unique=False)
    op.create_index(op.f('ix_user_layout_stats_user_id'), 'user_layout_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_layout_stats_user_id'), table_name='user_layout_stats')
    op.drop_index(op.f('ix_user_layout_stats_layout_id'), table_name='user_layout_stats')
    op.drop_table('user_layout_stats')
    # ### end Alembic commands ###
