"""add personal bests table

Revision ID: e08b9a327d94
Revises: b1598d12cee8
Create Date: 2026-08-23 19:12:44.023009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08b9a327d94'
down_revision: Union[str, Sequence[str], None] = 'b1598d12cee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_bests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('best_score_to_par', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'layout_id', name='uq_personal_bests_user_layout')
    )
    op.create_index(op.f('ix_personal_bests_layout_id'), 'personal_bests', ['layout_id'], unique=False)
    op.create_index(op.f('ix_personal_bests_user_id'), 'personal_bests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_bests_user_id'), table_name='personal_bests')
    op.drop_index(op.f('ix_personal_bests_layout_id'), table_name='personal_bests')
    op.drop_table('personal_bests')
    # ### end Alembic commands ###
